export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import  {AuthProvider}  from './Providers';
import "./globals.css"

import HeaderComp from './../components/common-ui/HeaderComp';
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
       <HeaderComp/>
       <div className="px-4">
        {children}
       </div>
        </AuthProvider>
        </body>
    </html>
  )
}
